<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{0a7fe922-6658-48a1-87b6-5b2f1ace9db1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_ALARMS();	//Chamada do programa Alarmes / call program ALARMS ]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>